### ISSUE TITLE
Traceback - exit whitout action

### ISSUE THREAD

**Issue by zerutek** [urwen/temper#5]
```
$ python3 --version
Python 3.5.3
```

```
$ ./temper.py --help
Traceback (most recent call last):
  File "./temper.py", line 410, in <module>
    temper = Temper()
  File "./temper.py", line 258, in __init__
    self.usb_devices = usblist.get_usb_devices()
  File "./temper.py", line 99, in get_usb_devices
    with os.scandir(Temper.SYSPATH) as it:
AttributeError: __exit__
```

**Comment by zerutek** [comment]
'wiryonolau' solve de problem.[Please merge in master](https://github.com/urwen/temper/pull/1)
